services:
  - type: web
    name: dream-korea
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install && npm run build && npm run seed || true
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
