// Statik kontent — koreys tili bo'yicha haqiqiy materiallar (so'zlar, grammatika, kitoblar, universitetlar).
// Kurslar/testlar/materiallar/videolar — MongoDB (admin /admin/content orqali boshqaradi).

export const vocabulary = [
  { ko: "사랑", tr: "사랑 — sarang", uz: "sevgi", level: "A1" },
  { ko: "학교", tr: "hakgyo", uz: "maktab", level: "A1" },
  { ko: "친구", tr: "chingu", uz: "do‘st", level: "A1" },
  { ko: "가족", tr: "gajok", uz: "oila", level: "A1" },
  { ko: "시간", tr: "sigan", uz: "vaqt", level: "A2" },
  { ko: "열심히", tr: "yeolsimhi", uz: "tirishtirib", level: "A2" },
  { ko: "꿈", tr: "kkum", uz: "orzu", level: "A1" },
  { ko: "한국어", tr: "hangugeo", uz: "koreys tili", level: "A1" },
];

export const grammarList = [
  { id: "1", title: "입니다", desc: "Bo‘lishlik qo‘shimchasi — rasmiy uslub", level: "A1" },
  { id: "2", title: "은 / 는", desc: "Mavzu yuklamasi", level: "A1" },
  { id: "3", title: "이 / 가", desc: "Ega yuklamasi", level: "A1" },
  { id: "4", title: "을 / 를", desc: "Tushum kelishigi", level: "A1" },
  { id: "5", title: "에", desc: "O‘rin-payt kelishigi", level: "A1" },
  { id: "6", title: "에서", desc: "Chiqish / o‘rin kelishigi", level: "A2" },
  { id: "7", title: "하고", desc: "Va, bilan", level: "A1" },
  { id: "8", title: "그리고", desc: "Va (gap bog‘lovchisi)", level: "A1" },
];

export type UniversityDetail = {
  id: string; name: string; city: string; programs: string[];
  topik: string; tuition: string; description: string;
  ranking: number; faculties: string[]; deadline: string; language: string;
  dorm: string; website: string; image: string;
  about: string; admission: string; scholarship: string;
};

export const universities: UniversityDetail[] = [
  { id: "1", name: "Seoul National University (SNU)", city: "Seoul", programs: ["Korean Language", "Engineering", "Business", "Medicine"], topik: "TOPIK 4", tuition: "$2,400 / yil", description: "Koreyaning #1 universiteti, QS World Top 40. Kuchli tadqiqot bazasi va xalqaro reyting.", ranking: 1, faculties: ["Humanities", "Engineering", "Medicine", "Business", "Natural Sciences"], deadline: "Mart / Sentabr", language: "Koreys / Ingliz", dorm: "Bor (oyiga ~$120)", website: "snu.ac.kr", image: "",
    about: "Seoul National University — Koreyaning eng nufuzli davlat universiteti, 1946-yilda tashkil etilgan. QS reytingida doimiy Top-40 ichida, Aziyada esa Top-3 da turadi. Kampus Gwanak, Seul janubida joylashgan: ulkan kutubxona, 100 dan ortiq tadqiqot laboratoriyalari va 18 000 talabalar uchun yotoqxona mavjud. Ilm-fan, muhandislik, huquq va tibbiyot yo‘nalishlari dunyo yetakchilari qatorida. Chet ellik talabalar uchun alohida Xalqaro bog‘lanish ofisi (OIA) hujjatlar, viza va yotoqxona bo‘yicha bepul yordam beradi. Bitiruvchilari Samsung, LG, Hyundai kabi kompaniyalarda yuqori lavozimlarda ishlaydi.",
    admission: "Hujjatlar: pasport nusxasi, attestat/diplom (apostil bilan), TOPIK sertifikati, motivatsion xat, 2 ta tavsiyanoma, moliyaviy kafolat (taxminan $10 000). Ariza muddati: mart (bahorgi qabul) va sentabr (kuzgi qabul). Hujjatlar onlayn (QS portal) orqali topshiriladi, so‘ng suhbat o‘tkaziladi. Ingliz tilidagi dasturlar uchun IELTS 6.5+ yoki TOEFL iBT 85+ talab qilinadi.",
    scholarship: "KGS (Korean Government Scholarship) — to‘liq kontrakt + oyiga ~$1 000 stipendiya + chipta. SNU Chairman Fellowship — eng yuqori ball olganlarga qo‘shimcha moliyaviy yordam. Universitet stipendiyasi: GPA 3.5+ bo‘lsa, kontraktni 30-100% qoplashi mumkin. O‘zbekiston talabalari uchun GKS dasturi eng ko‘p tanlanadigan yo‘l." },
  { id: "2", name: "Korea University", city: "Seoul", programs: ["Humanities", "Law", "Medicine", "Business"], topik: "TOPIK 4", tuition: "$2,700 / yil", description: "SKY uchligidan biri. Biznes, huquq va xalqaro aloqalar kuchli, katta stipendiya dasturlari.", ranking: 2, faculties: ["Law", "Business", "Medicine", "Korean Studies", "Engineering"], deadline: "Aprel / Oktabr", language: "Koreys / Ingliz", dorm: "Bor", website: "korea.ac.kr", image: "",
    about: "Korea University — 1905-yilda tashkil etilgan, Seuldagi eng qadimiy xususiy universitetlardan biri va SKY uchligiga kiradi (SNU, Korea, Yonsei). Anam-dong kampusi Seul markazida, Jongno tarixiy hududida. Biznes (Business School AACSB akkreditatsiyasi), huquq, jurnalistika va xalqaro aloqalar eng kuchli yo‘nalishlar. 30 000 dan ortiq talaba, 4 000 dan ortiq chet ellik talaba tahsil oladi. Sport jamoalari (Erkaklar futbol) universitet hayotida katta ahamiyatga ega. Samsung, SK, Hyundai bilan hamkorlikda amaliyot va ish o‘rinlari taqdim etiladi.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3-4 (ko‘pchilik dasturlar), motivatsion xat, tavsiyanoma xatlari, moliyaviy kafolat. Ariza: aprel va oktabr. Qabul jarayoni: hujjat tekshiruvi → yozma baholash (essay) → suhbat (onlayn yoki Seulda). Ingliz dasturlari uchun IELTS 6.0-6.5. Xalqaro qism (KIC) orqali TOPIK 3 bo‘lmaganlar uchun 1 yillik til kursi mavjud.",
    scholarship: "Korea University Scholarship — kontraktni 20-100% gacha qamrab oluvchi 20+ xil stipendiya. KGS hukumat stipendiyasi qabul qilinadi. To‘g‘ridan-to‘g‘ri kirish (Jolly Ha) dasturi — TOPIK 4+ va GPA 3.0+ bo‘lganlarga 50% chegirma. Yay va qishki maktablari ham subsidiyalangan." },
  { id: "3", name: "Yonsei University", city: "Seoul", programs: ["Business", "Korean Studies", "Engineering", "Medicine"], topik: "TOPIK 3", tuition: "$2,800 / yil", description: "SKY uchligi. Xalqaro almashinuv juda kuchli, DREAM KOREA talabalarini tez-tez qabul qiladi.", ranking: 3, faculties: ["Business", "Engineering", "Korean Language", "International Studies"], deadline: "Mart / Sentabr", language: "Koreys / Ingliz", dorm: "Bor", website: "yonsei.ac.kr", image: "",
    about: "Yonsei University — 1885-yilda tashkil etilgan Koreyaning eng qadimiy oliy ta’lim muassasasi, SKY uchligining a’zosi. Sinchon kampusi Seul g‘arbiyida, Shinchon metro bekati yonida. Meditsina va tibbiy fakultetlar milliy reytingda 1-o‘rinda, business school esa AACSB akkreditatsiyasiga ega. 3 500 dan ortiq chet ellik talaba 60 dan ortiq davlatdan kelib tahsil oladi. Global Partnership dasturi doirasida Yevropa, AQSh va Osiyo universitetlari bilan ikki tomonlama almashinuv mavjud. Kampusda muzey, teatr, basseyn va 10 dan ortiq talabalar klublari faoliyat yuritadi.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+ yoki IELTS 6.0+ (ingliz dasturlari), motivatsion xat, 2 tavsiyanoma, moliyaviy kafolat. Ariza muddati: mart va sentabr. Jarayon: onlayn ariza → hujjat baholash → suhbat (Zoom). Chet ellik talabalar uchun qo‘shimcha imtihon shart emas — faqat hujjat va suhbat baholanadi.",
    scholarship: "Yonsei International Scholarship — 30-100% kontrakt chegirmasi. GKS (Korean Government Scholarship) — to‘liq moliyalashtirish. Yonsei Dream Grant — O‘zbekiston kabi rivojlanayotgan mamlakatlar talabalari uchun alohida kvota. Yozgi til maktabi uchun ham alohida chegirmalar mavjud." },
  { id: "4", name: "Sungkyunkwan University (SKKU)", city: "Seoul", programs: ["Engineering", "Business", "Korean Language", "Design"], topik: "TOPIK 3", tuition: "$2,500 / yil", description: "Samsung homiyligida. Muhandislik va biznes yo‘nalishlari top-10 da, zamonaviy kampus.", ranking: 4, faculties: ["Engineering", "Business", "Design", "Korean Language"], deadline: "Aprel / Oktabr", language: "Koreys", dorm: "Bor", website: "skku.edu", image: "",
    about: "Sungkyunkwan University — 1398-yilda tashkil etilgan Koreyaning eng qadimiy universiteti (bugungi Koreya, Xitoy va Yaponiyadagi eng eski oliy ta’lim muassasasi). 1996-yildan beri Samsung Group homiyligi ostida: Samsung Advanced Institute of Technology, Samsung Medical Center va SKKU bilan birgalikda tadqiqot markazlari ishlaydi. Ingyeon kampusi Seul markazida, Sageun-dong esa Ilm-fan va muhandislik kampusi bo‘lib, nano-texnologiya, AI va sun’iy intellekt laboratoriyalari joylashgan. Business School — Koreyadagi eng qadimiy biznes maktabi.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 4+ (koreys tilidagi dasturlar) yoki IELTS 6.0+ (ingliz), motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: aprel va oktabr. Muhandislik yo‘nalishlari uchun qo‘shimcha portfolio yoki ilmiy ish tajribasi tavsiya etiladi.",
    scholarship: "SKKU International Scholarship — 25-100% chegirma (GPA va TOPIK asosida). Samsung Foundation stipendiyasi — eng yuqori ball olganlarga to‘liq kontrakt. GKS hukumat stipendiyasi qo‘llab-quvvatlanadi. 1-semesterda TOPIK 4 ga yetganlarga keyingi semestrda qo‘shimcha 50% chegirma beriladi." },
  { id: "5", name: "Hanyang University", city: "Seoul", programs: ["Engineering", "Architecture", "Business"], topik: "TOPIK 3", tuition: "$2,400 / yil", description: "Muhandislik bo‘yicha Koreya top-1, startap ekotizimi va ilmiy-patent faolligi kuchli.", ranking: 5, faculties: ["Engineering", "Architecture", "Business", "Humanities"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor", website: "hanyang.ac.kr", image: "",
    about: "Hanyang University — 1939-yilda tashkil etilgan xususiy universitet, muhandislik bo‘yicha Koreya top-3 da. Asosiy kampus Seul janubidagi Seongdong-gu hududida, ikkinchi kampus Ansan shahrida. Hanyang ERICA kampusi sanoat hamkorligi (Hyundai, POSCO, LG) bilan mashhur bo‘lib, talabalar amaliyotni o‘sha yerda o‘tashadi. Arxitektura, qurilish va robo-texnologiya yo‘nalishlari milliy reytingda yuqori. University-wide Start-up Incubator — talabalar startaplarini 3 yil davomida moliyaviy qo‘llab-quvvatlaydi.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: mart va sentabr. ERICA kampusi uchun alohida ariza — amaliyotga yo‘naltirilgan dasturlar uchun portfolio talab qilinishi mumkin.",
    scholarship: "Hanyang International Scholarship — kontraktni 30-100% qamrab oladi. Engineering Excellence Stipendiyasi — texnik yo‘nalish talabalari uchun. GKS va AAIK (Association of Asian International Students in Korea) dasturlari qo‘llab-quvvatlanadi. Talabalar ish dasturi (kampusda ishlash) haftasiga 20 soatgacha ruxsat etiladi." },
  { id: "6", name: "Kyung Hee University", city: "Seoul", programs: ["Hospitality", "Korean Language", "Medicine"], topik: "TOPIK 3", tuition: "$2,300 / yil", description: "Turizm va mehmondo‘stlik sohasida Asia top-1. Xalqaro konferens va madaniy tadbirlar markazi.", ranking: 6, faculties: ["Hospitality", "Korean Language", "Medicine", "Arts"], deadline: "May / Noyabr", language: "Koreys", dorm: "Bor", website: "khu.ac.kr", image: "",
    about: "Kyung Hee University — 1949-yilda tashkil etilgan, Seul sharqiyidagi Changsu-dong kampusi bilan mashhur. Global Hospitality & Tourism Management dasturi Osiyoda top-5 da. Universitet Seul, Yongin va Gyeongju shaharlarida uchta kampusga ega. Xalqaro Dunyo Kengashi (International Council) doirasida 60 dan ortiq mamlakat bilan hamkorlik bor. Medicine va Korean Studies yo‘nalishlari kuchli, madaniy meros va Koreya san’ati bo‘yicha xalqaro anjumanlar doimiy o‘tkaziladi. Kampusda «Grand Peace Palace» — Koreyaning eng yirik konferens zali joylashgan.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: may va noyabr. Hospitality dasturlari uchun suhbatda ingliz tili darajasi ham tekshiriladi (IELTS 5.5+ tavsiya etiladi).",
    scholarship: "Kyung Hee International Scholarship — 25-75% kontrakt chegirmasi. Turizm yo‘nalishi talabalari uchun hotel amaliyoti bilan birga stipendiya. GKS hukumat stipendiyasi mavjud. Talabalar uchun kampusda qisqa muddatli ish o‘rinlari taqdim etiladi." },
  { id: "7", name: "Busan National University", city: "Busan", programs: ["Engineering", "Korean Language", "Business"], topik: "TOPIK 3", tuition: "$1,700 / yil", description: "Busandagi davlat universiteti. Arzon kontrakt, dengiz bo‘yida, katta kampus.", ranking: 8, faculties: ["Engineering", "Korean Language", "Business", "Natural Sciences"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor (arzon)", website: "pusan.ac.kr", image: "",
    about: "Pusan National University (PNU) — Janubiy Koreyaning eng yirik davlat universitetlaridan biri, Busan shahrida, dengiz va tog‘lar orasidagi ulkan kampusda joylashgan. 1946-yilda tashkil etilgan, 2 000 dan ortiq professor-o‘qituvchi va 28 000 talaba. Muhandislik, dengiz ishlari, yadro fizikasi va logistika yo‘nalishlari kuchli — Busan porti bilan to‘g‘ridan-to‘g‘ri hamkorlik mavjud. Janubiy Koreya davlat universitetlari orasida kontrakt narxi eng arzonlardan biri, shu sababli byudjeti cheklangan talabalar orasida juda mashhur. Kampus metro liniyasi yonida, Seulga poyezd bilan 2.5 soat.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, moliyaviy kafolat (taxminan $8 000). Ariza: mart va sentabr. Qabul onlayn, suhbat shart emas — hujjatlar bahosi asosida. TOPIK 2 bo‘lganlar uchun 6 oylik koreys tili kursi (CPU) mavjud.",
    scholarship: "PNU Global Scholarship — kontraktni 30-100% qamrab oladi. Busan shahar stipendiyasi — shahar hududida yashash sharti bilan. GKS dasturi PNU uchun alohida kvotaga ega. Arzon yotoqxona (oyiga ~$80) va talabalar ovqatxonasi (bir vaqtlik ovqat ~$3) — umumiy xarajat Seulga nisbatan 40% arzon." },
  { id: "8", name: "Inha University", city: "Incheon", programs: ["Logistics", "Engineering"], topik: "TOPIK 3", tuition: "$2,000 / yil", description: "Logistika va muhandislik ixtisosligi. Incheon aeroporti va Xalqaro savdo hududiga yaqin.", ranking: 9, faculties: ["Logistics", "Engineering", "Business"], deadline: "Aprel / Oktabr", language: "Koreys", dorm: "Bor", website: "inha.ac.kr", image: "",
    about: "Inha University — 1954-yilda tashkil etilgan, Incheon shahrida, Inchon xalqaro aeroportidan 15 daqiqalik masofada joylashgan. Logistics & Supply Chain Management yo‘nalishi Osiyoda top-10 da — Samsung Heavy Industries, Hyundai Oilbank bilan hamkorlikda. Muhandislik, IT va biznes fakultetlari kuchli. Kampus zamonaviy laboratoriyalar va tadqiqot markazlari bilan jihozlangan. Chet ellik talabalar uchun koreys tili kursi (Inha Language Institute) mavjud.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: aprel va oktabr. Logistika yo‘nalishiga hujjat topshirayotganlar uchun matematika bo‘yicha qo‘shimcha test tavsiya etiladi.",
    scholarship: "Inha International Scholarship — 30-70% chegirma. Logistika va Engineering yo‘nalishlari uchun Samsung Foundation stipendiyasi. GKS dasturi qabul qilinadi. Talabalar uchun kampusta ish o‘rinlari mavjud." },
  { id: "9", name: "Chung-Ang University (CAU)", city: "Seoul", programs: ["Film & Arts", "Business", "Korean Language"], topik: "TOPIK 3", tuition: "$2,200 / yil", description: "Kino va san’at sohasida mashhur — ko‘plab aktyorlar shu yerda tahsil olgan.", ranking: 7, faculties: ["Film & Arts", "Business", "Korean Language"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor", website: "cau.ac.kr", image: "",
    about: "Chung-Ang University — 1918-yilda tashkil etilgan xususiy universitet, film, teatr va san’at yo‘nalishlarida Koreya top-1 da. Ko‘plab mashhur aktyorlar va rejissyorlar (masalan, Korean Wave yulduzlari) shu yerda tahsil olgan. Ikki kampus: Seul (Dongjak) va Anseong. Business School va Farmatsiya fakultetlari ham kuchli. Madaniy ijod, media va kommunikatsiya yo‘nalishlari uchun studiyalar va professional jihozlangan kinoteatrlar mavjud.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: mart va sentabr. Film & Arts dasturlari uchun qo‘shimcha portfolio (video, ijodiy ish) talab qilinishi mumkin.",
    scholarship: "CAU International Scholarship — 25-75% kontrakt chegirmasi. San’at yo‘nalishi talabalari uchun ijodiy stipendiya. GKS dasturi qabul qilinadi. Kampusda xalqaro talabalar uchun alohida qo‘llab-quvvatlash markazi mavjud." },
  { id: "10", name: "Sejong University", city: "Seoul", programs: ["Hotel & Tourism", "Business", "Korean Language"], topik: "TOPIK 3", tuition: "$1,900 / yil", description: "Turizm va mehmonxona ishi bo‘yicha amaliyotga yo‘naltirilgan, Seul markaziga yaqin.", ranking: 10, faculties: ["Hotel & Tourism", "Business", "Arts"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor", website: "sejong.ac.kr", image: "",
    about: "Sejong University — 1940-yilda tashkil etilgan, Seul janub-sharqiyidagi Gwangjin-gu hududida. Hotel & Tourism Management dasturi Koreyada top-3 da, amaliyotga katta ahamiyat beradi — talabalar Grand Hotel, Lotte va Hilton kabi mehmonxonalarda amaliyot o‘taydi. Business, Arts va Humanitarian yo‘nalishlari ham mavjud. Kampus metro bekatidan 5 daqiqada, Seul markaziga 20 daqiqada yetib boriladi.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, moliyaviy kafolat. Ariza: mart va sentabr. Hotel dasturlari uchun suhbatda ingliz tili darajasi tekshiriladi (IELTS 5.5+ yoki TOEFL iBT 71+ tavsiya etiladi).",
    scholarship: "Sejong International Scholarship — 20-60% chegirma. Hotel & Tourism yo‘nalishi uchun mehmonxona korxonasi bilan hamkorlikdagi stipendiya. GKS dasturi qabul qilinadi." },
  { id: "11", name: "Konkuk University", city: "Seoul", programs: ["Business", "Veterinary", "Korean Language"], topik: "TOPIK 3", tuition: "$2,000 / yil", description: "Biznes va veterinariya yo‘nalishlari kuchli. Keng kampus, ko‘l bo‘yida joylashgan.", ranking: 11, faculties: ["Business", "Veterinary", "Korean Language", "Arts"], deadline: "Aprel / Oktabr", language: "Koreys", dorm: "Bor", website: "konkuk.ac.kr", image: "",
    about: "Konkuk University — 1946-yilda tashkil etilgan, Seul sharqiyidagi Gwangjin-gu va Chungcheong (Sejong kampusi) hududida ikki kampusga ega. Veterinariya, farmatsiya va bio-texnologiya yo‘nalishlari Koreyada top-5 da. Business School ham kuchli, xalqaro biznes yo‘nalishida ingliz tilidagi dasturlar mavjud. Kampusda sun’iy ko‘l va keng yashil hudud bor — talabalar uchun qulay muhit.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, moliyaviy kafolat. Ariza: aprel va oktabr. Veterinariya yo‘nalishiga hujjat topshirayotganlar uchun biologiya bo‘yicha qo‘shimcha test tavsiya etiladi.",
    scholarship: "Konkuk International Scholarship — 25-60% kontrakt chegirmasi. Bio va veterinariya yo‘nalishlari uchun tadqiqot stipendiyasi. GKS dasturi qabul qilinadi." },
  { id: "12", name: "Ajou University", city: "Suwon", programs: ["Engineering", "Medicine", "Business"], topik: "TOPIK 3", tuition: "$1,900 / yil", description: "Suwon shahrida. Muhandislik va IT kuchli, Samsung bilan yaqin hamkorlik.", ranking: 12, faculties: ["Engineering", "IT", "Business", "Medicine"], deadline: "Mart / Sentabr", language: "Koreys / Ingliz", dorm: "Bor", website: "ajou.ac.kr", image: "",
    about: "Ajou University — 1973-yilda tashkil etilgan, Suwon shahrida (Seul janubidan 30 daqiqa). Samsung Electronics bilan yaqin hamkorlikda IT, elektronika va muhandislik yo‘nalishlari kuchli. Inha University bilan birgalikda logistika ham rivojlangan. Kampus zamonaviy laboratoriyalar, startap inkubator va xalqaro talabalar uchun alohida binoga ega. Medicine fakulteti klinik amaliyot bilan birga olib boriladi.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: mart va sentabr. Ingliz tilidagi dasturlar uchun IELTS 6.0+ talab qilinadi.",
    scholarship: "Ajou International Scholarship — 30-100% kontrakt chegirmasi. Samsung Foundation — IT va Engineering yo‘nalishlari uchun. GKS dasturi qabul qilinadi. Kampusda talabalar uchun ish o‘rinlari mavjud." },
  { id: "13", name: "Keimyung University", city: "Daegu", programs: ["Korean Language", "Business", "Arts"], topik: "TOPIK 2-3", tuition: "$1,500 / yil", description: "Daegu shahrida — arzon variant. Til kursi arzon va samarali, TOPIK ga tayyorgarlik kuchli.", ranking: 15, faculties: ["Korean Language", "Business", "Arts"], deadline: "Har chorak", language: "Koreys", dorm: "Bor (juda arzon)", website: "kmu.ac.kr", image: "",
    about: "Keimyung University — 1954-yilda tashkil etilgan xususiy universitet, Daegu shahrida (Seuldan 2 soat). Xalqaro tillar instituti chet ellik talabalar uchun koreys tili kurslarida ixtisoslashgan — har chorakda (4 marta yiliga) qabul mavjud. Business, Arts va Humanitarian yo‘nalishlari mavjud. Daegu — Seulgadan arzonroq shahar: yashash xarajati oyiga $500-600 atrofida. Kampus tog‘ etagida, tabiiy muhit va sport inshootlari bilan ajralib turadi.",
    admission: "Hujjatlar: pasport, attestat/diplom. TOPIK shart emas — kirish darajasi (TOPIK 0-1) bilan ham hujjat topshirish mumkin, so‘ng til kursida o‘qish boshlanadi. Ariza: har chorak (mart, iyun, sentabr, dekabr). Moliyaviy kafolat: taxminan $7 000.",
    scholarship: "Keimyung Language Scholarship — TOPIK ga kirgan darajasi bo‘yicha 20-50% chegirma. Til kursi kontrakti juda arzon (~$1 200/yil). Daegu shahar stipendiyasi — shaharda yashash sharti bilan. GKS dasturi qabul qilinadi." },
  { id: "14", name: "Chonnam National University", city: "Gwangju", programs: ["Korean Language", "Engineering", "Agriculture"], topik: "TOPIK 3", tuition: "$1,400 / yil", description: "Davlat universiteti — kontrakt eng arzonlardan. Qishloq xo‘jaligi va muhandislik kuchli.", ranking: 13, faculties: ["Engineering", "Korean Language", "Agriculture"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor", website: "jnu.ac.kr", image: "",
    about: "Chonnam National University — 1952-yilda tashkil etilgan davlat universiteti, Gwangju shahrida. Qishloq xo‘jaligi, oziq-ovqat texnologiyasi va muhandislik yo‘nalishlarida janubiy Koreya top-5 da. 24 000 talaba, 1 500 dan ortiq chet ellik talaba. Kampus Gwangju markazida, metro liniyasi yonida. Davlat universiteti bo‘lgani uchun kontrakt narxi eng arzon toifaga kiradi va o‘zbek talabalari orasida mashhur.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, moliyaviy kafolat. Ariza: mart va sentabr. TOPIK 2 bo‘lganlar uchun 1 semestrlik koreys tili kursi mavjud.",
    scholarship: "CNU Global Scholarship — 30-100% kontrakt chegirmasi. GKS dasturi uchun alohida kvota. Qishloq xo‘jaligi yo‘nalishida amaliyot bilan birga stipendiya. Yotoqxona arzon (oyiga ~$70)." },
  { id: "15", name: "Pusan National University (PNU)", city: "Busan", programs: ["Korean Language", "Engineering", "Medicine"], topik: "TOPIK 3", tuition: "$1,600 / yil", description: "PNU — Busan milliy universiteti, davlat. Dengiz manzarasi, arzon yashash.", ranking: 8, faculties: ["Engineering", "Medicine", "Korean Language"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor", website: "pusan.ac.kr", image: "",
    about: "Pusan National University — Janubiy Koreyaning eng yirik davlat universitetlaridan biri (asosiy kampus Busan shahrida). Muhandislik, tibbiyot, dengiz ishlari va tabiiy fanlar yo‘nalishlari kuchli. 28 000 talaba va 2 000 dan ortiq professor-o‘qituvchi. Kampus dengiz bo‘yida, Busan metro liniyasi yonida. Davlat universiteti bo‘lgani uchun kontrakt narxi arzon, yashash xarajati esa Seulga nisbatan 40% past.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, moliyaviy kafolat (taxminan $8 000). Ariza: mart va sentabr. Qabul onlayn, suhbat shart emas.",
    scholarship: "PNU Global Scholarship — kontraktni 30-100% qamrab oladi. Busan shahar stipendiyasi. GKS dasturi PNU uchun alohida kvotaga ega. Yotoqxona arzon, talabalar ovqatxonasi ham qulay narxlarda." },
  { id: "16", name: "Dankook University", city: "Yongin / Cheonan", programs: ["Architecture", "Korean Language", "Business"], topik: "TOPIK 3", tuition: "$1,800 / yil", description: "Arxitektura va dizayn yo‘nalishlari kuchli. Ikkita kampus: Yongin va Cheonan.", ranking: 14, faculties: ["Architecture", "Design", "Business", "Korean Language"], deadline: "Aprel / Oktabr", language: "Koreys", dorm: "Bor", website: "dankook.ac.kr", image: "",
    about: "Dankook University — 1947-yilda tashkil etilgan xususiy universitet, ikkita kampusda (Cheonan va Yongin) faoliyat yuritadi. Arxitektura, dizayn va muhandislik yo‘nalishlari kuchli. Cheonan kampusi zamonaviy laboratoriyalar va studiyalar bilan jihozlangan. Yongin kampusi Seul janubida, madaniy va ijodiy yo‘nalishlar uchun qulay. Xalqaro talabalar uchun koreys tili kursi va qo‘llab-quvvatlash dasturi mavjud.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, moliyaviy kafolat. Ariza: aprel va oktabr. Arxitektura yo‘nalishiga hujjat topshirayotganlar uchun portfolio talab qilinishi mumkin.",
    scholarship: "Dankook International Scholarship — 25-70% kontrakt chegirmasi. Arxitektura va dizayn yo‘nalishlari uchun ijodiy stipendiya. GKS dasturi qabul qilinadi." },
  { id: "17", name: "Hankuk University of Foreign Studies (HUFS)", city: "Seoul", programs: ["Korean Language", "Translation", "International Studies"], topik: "TOPIK 3", tuition: "$2,100 / yil", description: "Tillar universiteti — tarjimonlik va xalqaro aloqalar uchun ideal. 40+ til o‘qitiladi.", ranking: 6, faculties: ["Translation", "Korean Language", "International Studies"], deadline: "Mart / Sentabr", language: "Koreys / Ingliz", dorm: "Bor", website: "hufs.ac.kr", image: "",
    about: "Hankuk University of Foreign Studies — 1954-yilda tashkil etilgan, chet tillari va xalqaro aloqalar bo‘yicha ixtisoslashgan universitet. 40 dan ortiq til o‘qitiladi: ingliz, xitoy, yapon, arab, frantsuz, o‘zbek va boshqalar. Seul (Hyehwa) va Anseong kampuslari mavjud. Tarjimonlik, xalqaro biznes va diplomatiya yo‘nalishlari eng kuchli. BMT, xalqaro tashkilotlar va elchixonalar bilan hamkorlikda amaliyot dasturlari bor.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+ (koreys dasturlari) yoki IELTS 6.0+ (ingliz dasturlari), motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: mart va sentabr. Xalqaro aloqalar yo‘nalishida suhbatda ingliz tili darajasi tekshiriladi.",
    scholarship: "HUFS International Scholarship — 30-100% kontrakt chegirmasi. Tarjimonlik yo‘nalishi uchun alohida stipendiya. GKS dasturi qabul qilinadi. Talabalar uchun xalqaro tashkilotlarda amaliyot imkoniyati mavjud." },
  { id: "18", name: "Kookmin University", city: "Seoul", programs: ["Design", "Engineering", "Business"], topik: "TOPIK 3", tuition: "$1,900 / yil", description: "Dizayn va avtomobilsozlik (Hyundai/Kia hamkor). Seul markaziga yaqin kampus.", ranking: 11, faculties: ["Design", "Engineering", "Business"], deadline: "Mart / Sentabr", language: "Koreys", dorm: "Bor", website: "kookmin.ac.kr", image: "",
    about: "Kookmin University — 1946-yilda tashkil etilgan xususiy universitet, Seul janubidagi Seongdong-gu hududida. Dizayn, avtomobilsozlik va muhandislik yo‘nalishlari Hyundai/Kia bilan hamkorlikda rivojlangan. Business School ham kuchli, xalqaro biznes yo‘nalishida ingliz tilidagi dasturlar mavjud. Kampus Seul markaziga yaqin, metro liniyasi yonida. Talabalar uchun startap inkubator va dizayn studiyalari mavjud.",
    admission: "Hujjatlar: pasport, attestat/diplom, TOPIK 3+, motivatsion xat, tavsiyanoma, moliyaviy kafolat. Ariza: mart va sentabr. Dizayn yo‘nalishiga hujjat topshirayotganlar uchun portfolio talab qilinishi mumkin.",
    scholarship: "Kookmin International Scholarship — 25-70% kontrakt chegirmasi. Dizayn va muhandislik yo‘nalishlari uchun Hyundai/Kia stipendiyasi. GKS dasturi qabul qilinadi." },
];

export const books = [
  { id: "1", title: "TOPIK I — Reading", level: "TOPIK I", pages: 320, color: "from-blue-600 to-indigo-600" },
  { id: "2", title: "Korean Grammar in Use — Beginner", level: "A1-A2", pages: 408, color: "from-emerald-600 to-teal-600" },
  { id: "3", title: "EPS-TOPIK Standard Textbook", level: "EPS", pages: 280, color: "from-violet-600 to-purple-600" },
  { id: "4", title: "Vocabulary 2000 — Essential Words", level: "A1-B1", pages: 360, color: "from-rose-600 to-pink-600" },
];
